-- Load DEPARTMENT
LOAD DATA LOCAL INFILE 'department.csv'
INTO TABLE DEPARTMENT
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load DOCTOR
LOAD DATA LOCAL INFILE 'doctor.csv'
INTO TABLE DOCTOR
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load NURSE
LOAD DATA LOCAL INFILE 'nurse.csv'
INTO TABLE NURSE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load ROOM
LOAD DATA LOCAL INFILE 'room.csv'
INTO TABLE ROOM
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load PATIENT
LOAD DATA LOCAL INFILE 'patient.csv'
INTO TABLE PATIENT
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;